name: Ata de reunião.
description: O objetivo principal deste issue template é auxiliar na elaboração de atas de reunião.
title: '[DD/MM/AAAA] Reunião XXXXX'
labels: ['reuniao']
projects: ['splor-mg/13']
body:
  - type: textarea
    id: descricao
    validations:
      required: true
    attributes:
      label: Descrição
      description: Descreva seu reunião com o maior número de detalhes possíveis.
      value: |
        [Gravação do encontro]().

        ## Pauta
        - Tempo estimado: em minutos
        - Pauta 1
        - Pauta 2

        ## Participantes
        - Participante 1
        - Participante 2

        ## Assuntos tratados
        - Tópico 1
        - Tópico 2

        ## Dúvidas
        - Decisão 1
        - Decisão 2

        ## Ideias / Ações
        - [ ] Pendência 1
        - [ ] Pendência 2
