name: Ata live code.
description: O objetivo principal deste issue template é auxiliar na elaboração de atas de nossos encontros live code.
title: "[DD/MM/AAAA] Live Code XXXXX"
labels: ["reuniao"]
projects: ["splor-mg/13"]
body:
  - type: textarea
    id: descricao
    validations:
      required: true
    attributes:
      label: Descrição
      description: Descreva seu reunião com o maior número de detalhes possíveis.
      value: |
        [Gravação do encontro]().

        ## Descrição

        ## Ações
        - [ ] Incluir video do encontro YouTube.
        - [ ] Incluir transcrição do vídeo em repositório GitHub.
        - [ ] Incluir Post Handbook.
