name: Issue template AID.
description: Issue template AID.
projects: ["splor-mg/13"]
body:
  - type: textarea
    id: descricao
    attributes:
      label: Descrição
      description: Descreva seu Issue com o maior número de detalhes possíveis. 
      placeholder: Encontrei o erro / Tive a ideia / Etc...
    validations:
      required: true
  - type: textarea
    id: atividades_correcoes
    attributes:
      label: Lista de atividades e/ou correções
      description: Liste abaixo todas as atividades e/ou correções necessárias antes do fechamento do Issue.
      value: |
        - [ ] Atividade/Correção 1
        - [ ] Atividade/Correção 2
        - [ ] Atividade/Correção 3
  - type: dropdown
    id: participantes
    attributes:
      label: Participantes
      description: Lista os prováveis participantes da equipe neste Issue.
      options: ['@splor-mg/aid', '@labanca', '@carloshob', '@gabrielbdornas', '@hslinhares']
      multiple: true

