name: AID Issue template.
description: AID Issue template.
projects: ["splor-mg/13"]
body:
  - type: textarea
    id: descricao
    attributes:
      label: Descrição
      description: Descreva seu Issue com o maior número de detalhes possíveis. 
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: atividades_correcoes
    attributes:
      label: Lista de atividades e correções
      description: Liste abaixo todas as atividades e/ou correções necessárias antes do fechamento do Issue.
      value: |
        - [ ] Atividade/Correção 1
        - [ ] Atividade/Correção 2
        - [ ] Atividade/Correção 3
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
